### ISSUE TITLE
chore: make directories uniform naming

### ISSUE THREAD

**Issue by leviking** [leviking/legendary-palm-tree#10]

**Comment by localpath** [comment]
i think we should use all lowercase names for dirname

**Comment by techieeliot** [comment]
Should we name the files with spaces or use underscores? @leviking

**Comment by MDutro** [comment]
First name or last name?

**Comment by leviking** [comment]
all lowercase, first name

**Comment by localpathcomp** [comment]
i vote for dashes/spaces
